version = "0.3.2"

[scripts]
serve.generic = "tailwindcss --watch -i ./index.css -o ./tailwind.css & trunk serve"
serve.targets.windows = [
	"Start-Process -NoNewWindow \"cmd.exe\" \"tailwindcss --watch -o ./tailwind.css\"",
	"trunk serve",
]

build.generic = ["tailwindcss -i ./index.css -o ./tailwind.css", "trunk build"]
