[package]
name = "portfolio-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo-utils = "0.1.5"
log = "0.4.17"
wasm-logger = "0.2.0"
yew = "0.19.3"
