name: Rust

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: rustup target add wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - uses: jetli/trunk-action@v0.1.0

      - name: get-yarn-deps
        run: yarn
      - name: compile tailwind
        run: yarn run tailwindcss -i ./index.css -o ./tailwind.css
      - name: build
        run: trunk build --release
      - name: test
        run: cargo test --verbose
