name: Rust

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: get-trunk
        run: cargo install trunk --locked
      - name: get-yarn-deps
        run: yarn
      - name: compile tailwind
        run: tailwindcss -i ./index.css -o ./tailwind.css
      - name: build
        run: trunk build --release
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: test
        run: cargo test --verbose
